/**
 * Static site strings — all UI text in one place.
 * Edit here to change any text, or via the Visual CMS in admin mode.
 */
export const STRINGS = {
  nav: {
    home: 'Home',
    about: 'About',
    services: 'Services',
    products: 'Products',
    projects: 'Projects',
    gallery: 'Gallery',
    blog: 'Blog',
    contact: 'Contact',
    getQuote: 'Get Quote',
  },
  hero: {
    badge: 'UPNEDA Authorized · PM Surya Ghar Yojana',
    cta1: 'Get Free Quote',
    cta2: 'Call Now',
  },
  about: {
    badge: 'About Us',
    title: "Varanasi's Trusted Solar Partner",
    subtitle: 'UPNEDA authorized solar EPC company specializing in rooftop solar, subsidy assistance, and net metering.',
    p1: 'Ashish Enterprises is a UPNEDA authorized solar EPC company serving Varanasi and Eastern Uttar Pradesh. We provide rooftop solar installations, PM Surya Ghar Yojana subsidy assistance, net metering setup, and comprehensive solar maintenance services.',
    p2: 'Our journey began with a simple belief: every household deserves affordable, reliable, and clean energy. With 500+ installations and 850+ kW of solar capacity deployed, we have helped our customers save lakhs on electricity bills.',
    highlights: ['UPNEDA Authorized', '50+ Expert Team', '99.5% Satisfaction'] as string[],
  },
  services: {
    badge: 'Our Services',
    title: 'Complete Solar & Electrical Solutions',
    subtitle: 'From residential rooftops to commercial installations, we deliver end-to-end solutions.',
    learnMore: 'Learn More',
    viewAll: 'View All Services',
  },
  benefits: {
    badge: 'Why Choose Us',
    title: 'The Ashish Enterprises Advantage',
    subtitle: 'We go above and beyond to deliver exceptional value, quality, and service.',
  },
  projects: {
    badge: 'Our Projects',
    title: 'Proven Track Record of Excellence',
    subtitle: "See how we've helped businesses and homeowners harness the power of the sun.",
    viewAll: 'View All Projects',
  },
  testimonials: {
    badge: 'Testimonials',
    title: 'What Our Clients Say',
    subtitle: 'Real stories from real customers who trusted us with their energy needs.',
  },
  faq: {
    badge: 'FAQs',
    title: 'Frequently Asked Questions',
    subtitle: 'Find answers to the most common questions about solar energy and our services.',
    viewAll: 'View All FAQs',
  },
  contact: {
    badge: 'Get In Touch',
    title: 'Ready to Go Solar?',
    subtitle: 'Fill out the form and our team will get back to you within 24 hours with a free customized quote.',
    sendMessage: 'Send Message',
    thankYou: 'Thank You!',
    thankYouMsg: "Your message has been sent. We'll get back to you within 24 hours.",
    callUs: 'Call Us',
    emailUs: 'Email',
    visitUs: 'Visit Us',
    whatsapp: 'WhatsApp Us',
    businessHours: 'Business Hours',
    monSat: 'Monday – Saturday',
    sunday: 'Sunday',
    byAppointment: 'By Appointment',
  },
  footer: {
    aboutUs: 'About Us',
    quickLinks: 'Quick Links',
    services: 'Services',
    contactUs: 'Contact Us',
    newsletter: 'Stay updated with our latest projects',
    rights: 'All rights reserved.',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
  },
  forms: {
    name: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    service: 'Service Required',
    message: 'Your Message',
    selectService: 'Select a service',
    submit: 'Submit',
    required: 'This field is required',
  },
  common: {
    loading: 'Loading...',
    error: 'Something went wrong',
    tryAgain: 'Try Again',
    viewDetails: 'View Details',
    readMore: 'Read More',
    callNow: 'Call Now',
    getQuote: 'Get Free Quote',
  },
  pages: {
    aboutTitle: 'About Ashish Enterprises',
    aboutSubtitle: 'UPNEDA authorized solar EPC company serving Varanasi & Eastern UP since 2016.',
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Comprehensive solar and electrical solutions for homes, businesses, and industries.',
    productsTitle: 'Our Products',
    productsSubtitle: 'Premium quality solar panels, inverters, batteries, and accessories.',
    projectsTitle: 'Our Projects',
    projectsSubtitle: 'Explore our portfolio of successful solar installations across Varanasi region.',
    galleryTitle: 'Photo Gallery',
    gallerySubtitle: 'A visual journey through our solar installations and projects.',
    blogTitle: 'Blog & Resources',
    blogSubtitle: 'Stay informed with the latest news, tips, and insights about solar energy.',
    contactTitle: 'Contact Us',
    contactSubtitle: 'Have questions about solar energy? We are here to help.',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Find answers to common questions about solar energy, installations, and our services.',
  },
  team: {
    badge: 'Our Team',
    title: 'Meet the Experts',
    subtitle: 'Our team brings years of combined experience in solar engineering and customer service.',
  },
  mission: {
    title: 'Our Mission',
    content: 'To make solar energy accessible and affordable for every household and business in Eastern UP, delivering world-class quality with exceptional service.',
  },
  vision: {
    title: 'Our Vision',
    content: 'To be the most trusted solar energy partner in Uttar Pradesh, leading the clean energy revolution with integrity and innovation.',
  },
} as const;
